name: Workflows with large secrets

on:
 workflow_dispatch:
    inputs:
      var_name:
        description: 'CONFIG_DEV || TOKEN'     
        required: true
jobs:
  get-secrets-vars:
    name: Get Secrets Vars
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        env:
         SUPER_SECRET: ${{ secrets.TESTE1 }}
        run: echo $SUPER_SECRET > $HOME/testeSecret.txt
      - run: cat $HOME/testeSecret.txt
