name: Workflows with large secrets

on:
 workflow_dispatch:
    inputs:
      var_name:
        description: 'CONFIG_DEV || TOKEN'     
        required: true
jobs:
  get-secrets-vars:
    name: Get Secrets Vars
    runs-on: ubuntu-latest
    steps:
      - name: Get Secrets Vars
        run: mkdir $HOME/secrets| echo ${{ secrets.TESTE1}} > $HOME/secrets/my_secret.txt | cat $HOME/secrets/my_secret.txt
